time-format %s
date-format %s
log-format {"level":"%^","ts":%x.%^,"logger":"%^","msg":"%^","request":{"remote_ip":"%^","remote_port":"%^","client_ip":"%h","proto":"%H","method":"%m","host":"%v","uri":"%U"},"bytes_read":%^,"user_id":"%^","duration":%T,"size":%b,"status":%s}
